import fs from 'fs';
const path='server.js';
let s=fs.readFileSync(path,'utf8');
function replaceBetween(startMarker,endMarker,replacement){const a=s.indexOf(startMarker);const b=s.indexOf(endMarker,a);if(a<0||b<0)throw new Error(`Cannot patch ${startMarker}`);s=s.slice(0,a)+replacement+'\n'+s.slice(b);}
function insertBefore(marker,text){const i=s.indexOf(marker);if(i<0)throw new Error(`Cannot insert before ${marker}`);s=s.slice(0,i)+text+s.slice(i);}
replaceBetween('function botDraft(', 'function allDrafted', `function botDraft(r){r.draftBotToken=(r.draftBotToken||0)+1;const token=r.draftBotToken;const stage=r.draftStage;r.players.filter(p=>p.bot&&!p.kicked).forEach((p,i)=>setTimeout(()=>{if(r.status!=='draft'||r.draftBotToken!==token||r.draftStage!==stage)return;const h=r.draftHands[p.id]||[];const expected=stage===1?3:2;if(h.length!==expected)return;const c=h.slice().sort((a,b)=>scoreCard(b)-scoreCard(a))[0];if(c)pickDraft(r,p,c.id)},400+i*220))}`);
replaceBetween('function passDraft(', 'function pickDraft', `function passDraft(r){const ids=r.players.filter(p=>!p.kicked).map(p=>p.id),old=r.draftHands,next={};ids.forEach((id,i)=>{const remaining=(old[id]||[]).slice();if(remaining.length!==2)throw new Error('Draft pass error: expected 2 cards before passing');next[ids[(i-1+ids.length)%ids.length]]=remaining});r.draftHands=next;r.draftStage=2;push(r,'Vòng chọn 2: mỗi người giữ 1 lá và chuyền đúng 2 lá còn lại cho người bên tay phải.');sync(r);botDraft(r)}`);
replaceBetween('function pickDraft(', 'function beginNight', `function pickDraft(r,p,id){if(r.status!=='draft'||p.kicked)return;const active=r.players.filter(x=>!x.kicked);const h=r.draftHands[p.id]||[];const expected=r.draftStage===1?3:2;if(h.length!==expected)return;const i=h.findIndex(c=>c.id===id);if(i<0)return;r.kept[p.id].push(h.splice(i,1)[0]);if(active.every(x=>(r.kept[x.id]||[]).length>=r.draftStage)){if(r.draftStage===1)passDraft(r);else{active.forEach(x=>{const left=r.draftHands[x.id]||[];if(left.length!==1)throw new Error('Draft finish error: expected exactly 1 discarded card');r.discarded.push(...left);x.hand=(r.kept[x.id]||[]).slice(0,2)});beginNight(r)}}else sync(r)}`);
replaceBetween('function play(', 'function skip', `function play(r,p,m){if(!p.alive||p.kicked||r.reaction||r.grave||!r.pending?.has(p.id)){send(p,'error',{message:'Bạn không thể thực hiện hành động này lúc này.'});return}const i=p.hand.findIndex(c=>c.id===m.cardId&&c.type===r.phase);if(i<0){send(p,'error',{message:'Lá này không thuộc pha hiện tại hoặc đã được sử dụng.'});return}const c=p.hand[i];if(c.original==='Shapeshifter'){const ids=[...new Set(Array.isArray(m.targetIds)?m.targetIds:[])];const valid=ids.length===2&&ids.every(id=>id!==p.id&&getP(r,id)?.alive&&!getP(r,id)?.kicked);if(!valid){send(p,'error',{message:'Kẻ biến hình cần chọn đúng 2 người chơi còn sống.'});return}}const removed=p.hand.splice(i,1)[0];r.pending.delete(p.id);r.queue.push({pid:p.id,card:removed,targetId:m.targetId,targetIds:m.targetIds||[],kill:!!m.kill});push(r,p.name+' đã khóa một lá.');sync(r);if(!r.pending.size)revealPhase(r)}`);
insertBefore("if(m.type==='start')", "if(m.type==='kick'){kickPlayer(r,me,m.targetId);return;}if(m.type==='start'){if(r.status==='lobby'&&r.players.length>=4)startRound(r);return;}if(m.type==='pause'){if(r.status==='night'||r.status==='draft'){r.pausedFrom=r.status;r.status='paused';sync(r)}else if(r.status==='paused'){r.status=r.pausedFrom||'lobby';r.pausedFrom=null;sync(r);if(r.status==='draft')botDraft(r);else if(r.status==='night'){if((r.queue||[]).length&&r.resolving>=0)setTimeout(()=>resolveNext(r),100);else preparePhase(r)}}return;}if(m.type==='end'){r.status='ended';push(r,'Game đã kết thúc.');sync(r);return;}if(m.type==='continueRound'){if(r.status==='round_end')startRound(r);return;}");
fs.writeFileSync(path,s);