import express from 'express';
import http from 'http';
import crypto from 'crypto';
import {WebSocketServer} from 'ws';
const app=express();app.use(express.static('public'));const server=http.createServer(app),wss=new WebSocketServer({server}),rooms=new Map();
const phases=['SPY','MYSTIC','TRICKSTER','BLIND ASSASSIN','SHINOBI'];
const uid=()=>crypto.randomBytes(5).toString('hex');
const send=(p,type,data={})=>p?.ws?.readyState===1&&p.ws.send(JSON.stringify({type,...data}));
const pub=p=>({id:p.id,name:p.name,alive:p.alive,honor:p.honor,connected:!!p.ws,bot:!!p.bot,ronin:!!p.ronin});
function state(r){return {code:r.code,status:r.status,phase:r.phase,round:r.round,host:r.host,players:r.players.map(pub),log:r.log.slice(-30),winner:r.winner,ronin:r.players.find(p=>p.ronin)?.id||null,revealed:r.revealed||[],resolving:r.resolving??-1,resolvingPid:r.resolvingPid||null,pendingCount:r.pending?.size||0};}
function push(r,t){r.log.push(t)}
function sync(r){r.players.forEach(p=>{send(p,'state',{room:state(r)});send(p,'private',{house:p.house,rank:p.rank,ronin:!!p.ronin,honor:p.honor,alive:p.alive,hand:p.hand||[],known:p.known||[],draft:r.draftHands?.[p.id]||[]});});}
function makeDeck(){const a=[];for(let n=1;n<=6;n++){a.push({id:uid(),type:'SPY',num:n,name:'Gián điệp',text:'Xem thẻ Nhà của một người chơi khác.'});a.push({id:uid(),type:'MYSTIC',num:n,name:'Nhà tiên tri',text:'Xem thẻ Nhà và 1 thẻ Ninja của một người chơi khác.'});a.push({id:uid(),type:'BLIND ASSASSIN',num:n,name:'Sát thủ mù',text:'Chọn một người chơi và giết họ.'});a.push({id:uid(),type:'SHINOBI',num:n,name:'Ninja',text:'Chọn một người, xem thẻ Nhà của họ; có thể giết họ.'});}
const tricks=[['Shapeshifter','Kẻ biến hình','Xem Nhà của 2 người rồi bí mật đổi chỗ 2 thẻ Nhà. Hai người đó không được xem Nhà mới.'],['Gravedigger','Kẻ đào mộ','Xem các Ninja đã bị loại khỏi draft và lấy 1 lá.'],['Troublemaker','Kẻ gây rối','Xem Nhà của một người và có thể công khai thông tin đó.'],['Spirit Merchant','Thương nhân linh hồn','Xem thẻ Nhà hoặc token Danh dự của một người chơi.'],['Thief','Kẻ trộm','Lộ thẻ Nhà của mình; có thể lấy 1 token Danh dự từ người có nhiều hơn mình.'],['Judge','Quan tòa','Xem thẻ Nhà của một người và có thể giết họ.']];
tricks.forEach((x,i)=>a.push({id:uid(),type:'TRICKSTER',num:i+1,name:x[1],original:x[0],text:x[2]}));
a.push({id:uid(),type:'MIRROR MONK',name:'Tăng lữ Gương',text:'Phản ứng khi bị Sát thủ mù hoặc Ninja chọn giết.'});a.push({id:uid(),type:'MARTYR',name:'Kẻ tử vì đạo',text:'Phản ứng khi bị Sát thủ mù hoặc Ninja chọn giết.'});a.push({id:uid(),type:'MASTERMIND',name:'Kẻ chủ mưu',text:'Lộ lá này cuối vòng nếu còn sống; hiệu ứng đặc biệt tại House Reveal.'});return a.sort(()=>Math.random()-.5)}
function makeHouses(n){const a=[],team=Math.floor(n/2);for(let i=1;i<=team;i++)a.push({house:'Lotus',rank:i,ronin:false});for(let i=1;i<=team;i++)a.push({house:'Crane',rank:i,ronin:false});if(n%2)a.push({house:null,rank:null,ronin:true});return a.sort(()=>Math.random()-.5)}
function startRound(r){r.status='draft';r.round++;r.phase=null;r.phaseIndex=0;r.log=[];r.winner=null;r.reaction=null;r.revealed=[];r.resolving=-1;r.resolvingPid=null;const hs=makeHouses(r.players.length);r.deck=makeDeck();r.draftHands={};r.kept={};r.draftStage=1;r.discarded=[];r.players.forEach((p,i)=>{const h=hs[i];p.house=h.house;p.rank=h.rank;p.ronin=h.ronin;p.alive=true;p.hand=[];p.known=[];p.honor=p.honor||0;r.draftHands[p.id]=[r.deck.pop(),r.deck.pop(),r.deck.pop()];r.kept[p.id]=[]});push(r,`Vòng ${r.round}: phát Nhà bí mật và 3 lá Ninja.`);sync(r);botDraft(r)}
function scoreCard(c){if(!c)return 0;if(c.type==='SHINOBI')return 8;if(c.type==='BLIND ASSASSIN')return 7;if(c.type==='MYSTIC')return 6;if(c.type==='SPY')return 5;if(c.type==='TRICKSTER')return 4;return 3}
function botDraft(r){r.players.filter(p=>p.bot).forEach((p,i)=>setTimeout(()=>{if(r.status!=='draft')return;const h=r.draftHands[p.id]||[];if(!h.length)return;const c=h.slice().sort((a,b)=>scoreCard(b)-scoreCard(a))[0];pickDraft(r,p,c.id)},400+i*220))}
function allDrafted(r){return r.players.every(p=>(r.kept[p.id]||[]).length>=r.draftStage)}
function passDraft(r){const ids=r.players.map(p=>p.id),old=r.draftHands,next={};ids.forEach((id,i)=>{const receiver=ids[(i+1)%ids.length];next[receiver]=(old[id]||[]).slice()});r.draftHands=next;r.draftStage=2;push(r,'Vòng chọn 2: nhận 2 lá từ bên phải, giữ 1 lá và bỏ lá còn lại.');sync(r);botDraft(r)}
function pickDraft(r,p,cardId){if(!p||!cardId)return;const h=r.draftHands[p.id]||[],i=h.findIndex(c=>c.id===cardId);if(i<0)return;const c=h.splice(i,1)[0];r.kept[p.id].push(c);if(allDrafted(r)){if(r.draftStage===1)passDraft(r);else{r.players.forEach(x=>{if(r.draftHands[x.id]?.length)r.discarded.push(...r.draftHands[x.id]);x.hand=(r.kept[x.id]||[]).slice(0,2)});beginNight(r)}}else sync(r)}
function beginNight(r){r.status='night';r.phaseIndex=0;r.phase=phases[0];r.queue=[];r.revealed=[];r.resolving=-1;r.resolvingPid=null;push(r,'Đêm bắt đầu. Được phép nói chuyện, bluff và đánh lạc hướng.');sync(r);preparePhase(r)}
function preparePhase(r){r.pending=new Set(r.players.filter(p=>p.alive&&p.hand.some(c=>c.type===r.phase)).map(p=>p.id));r.queue=[];r.revealed=[];r.resolving=-1;r.resolvingPid=null;sync(r);botPhase(r);if(r.pending.size===0)setTimeout(()=>revealPhase(r),150)}
function botPhase(r){if(r.status!=='night'||r.reaction)return;r.players.filter(p=>p.bot&&p.alive&&r.pending.has(p.id)).forEach((p,i)=>setTimeout(()=>{if(r.status!=='night'||r.phase!=='SPY'&&r.phase!=='MYSTIC'&&r.phase!=='TRICKSTER'&&r.phase!=='BLIND ASSASSIN'&&r.phase!=='SHINOBI'||!r.pending.has(p.id))return;const c=p.hand.find(x=>x.type===r.phase);if(!c)return;const targets=r.players.filter(x=>x.alive&&x.id!==p.id),t=targets.length?targets[Math.floor(Math.random()*targets.length)]:p;let kill=c.type==='SHINOBI'?Math.random()<.55:c.type==='BLIND ASSASSIN'||c.original==='Judge';let targetIds=[];if(c.original==='Shapeshifter'){const two=r.players.filter(x=>x.alive&&x.id!==p.id).slice(0,2);targetIds=two.map(x=>x.id)}p.hand.splice(p.hand.indexOf(c),1);r.queue.push({pid:p.id,card:c,targetId:t?.id,targetIds,kill});r.pending.delete(p.id);push(r,`🤖 ${p.name} đã khóa một lá.`);sync(r);if(r.pending.size===0)revealPhase(r)},550+i*250))}
function play(r,p,m){if(!p.alive||!r.pending.has(p.id))return;const i=p.hand.findIndex(c=>c.id===m.cardId&&c.type===r.phase);if(i<0)return;const c=p.hand.splice(i,1)[0];r.pending.delete(p.id);r.queue.push({pid:p.id,card:c,targetId:m.targetId,targetIds:m.targetIds||[],kill:!!m.kill});push(r,`${p.name} đã khóa một lá.`);sync(r);if(r.pending.size===0)revealPhase(r)}
function skip(r,p){if(!r.pending.has(p.id))return;r.pending.delete(p.id);p.hand=p.hand.filter(c=>c.type!==r.phase);push(r,`${p.name} bỏ qua ${phaseVi(r.phase)}.`);sync(r);if(r.pending.size===0)revealPhase(r)}
function phaseVi(x){return ({SPY:'Gián điệp',MYSTIC:'Nhà tiên tri',TRICKSTER:'Kẻ lừa đảo','BLIND ASSASSIN':'Sát thủ mù',SHINOBI:'Ninja'})[x]||x}
function getP(r,id){return r.players.find(p=>p.id===id)}
function revealPhase(r){if(r.status!=='night'||r.reaction)return;if(!r.queue.length)return advancePhase(r);r.queue.sort((a,b)=>(a.card.num||99)-(b.card.num||99));r.revealed=r.queue.map(x=>({pid:x.pid,playerName:getP(r,x.pid)?.name||'?',card:{type:x.card.type,num:x.card.num,name:x.card.name}}));r.resolving=0;r.resolvingPid=null;push(r,'Tất cả lá đã được mở cùng lúc. Bắt đầu hành động theo số trên lá: 1 → 6.');sync(r);setTimeout(()=>resolveNext(r),900)}
function resolveNext(r){if(r.status!=='night'||r.reaction)return;if(r.resolving>=r.queue.length){r.queue=[];r.revealed=[];r.resolving=-1;r.resolvingPid=null;sync(r);return advancePhase(r)}const q=r.queue[r.resolving];r.resolvingPid=q.pid;sync(r);setTimeout(()=>{if(r.status!=='night'||r.reaction)return;resolveCard(r,q);r.resolving++;r.resolvingPid=null;sync(r);setTimeout(()=>resolveNext(r),700)},700)}
function resolveCard(r,q){const p=getP(r,q.pid);if(!p||!p.alive)return;const t=getP(r,q.targetId);if(q.card.type==='SPY'){if(t&&t.alive)p.known.push({name:t.name,house:t.house,rank:t.rank,ronin:t.ronin});}else if(q.card.type==='MYSTIC'){if(t&&t.alive){const n=t.hand.find(c=>['SPY','MYSTIC','TRICKSTER','BLIND ASSASSIN','SHINOBI'].includes(c.type));p.known.push({name:t.name,house:t.house,rank:t.rank,ronin:t.ronin,ninja:n?.name||'Không có'});}}else if(q.card.type==='TRICKSTER')resolveTrick(r,q,p,t);else if(q.card.type==='BLIND ASSASSIN'){if(t&&t.alive)kill(r,t);}else if(q.card.type==='SHINOBI'){if(t&&t.alive){p.known.push({name:t.name,house:t.house,rank:t.rank,ronin:t.ronin});if(q.kill)kill(r,t);}}}
function resolveTrick(r,q,p,t){const n=q.card.original;if(n==='Shapeshifter'){const a=getP(r,q.targetIds?.[0]),b=getP(r,q.targetIds?.[1]);if(a&&b&&a!==b){[a.house,a.rank,a.ronin,b.house,b.rank,b.ronin]=[b.house,b.rank,b.ronin,a.house,a.rank,a.ronin];push(r,`${p.name} đã bí mật đổi Nhà của hai người.`)}}else if(n==='Gravedigger'){if(r.discarded.length)p.hand.push(r.discarded.splice(Math.floor(Math.random()*r.discarded.length),1)[0]);}else if(t&&n==='Troublemaker'){p.known.push({name:t.name,house:t.house,rank:t.rank,ronin:t.ronin});push(r,`${p.name} đã xem Nhà của ${t.name}.`)}else if(t&&n==='Thief'){if(t.honor>p.honor){t.honor--;p.honor++;push(r,`${p.name} đã lấy 1 Danh dự.`)}}else if(t&&n==='Judge')kill(r,t)}
function kill(r,t){if(!t||!t.alive)return;t.alive=false;push(r,`${t.name} bị hạ.`)}
function advancePhase(r){r.phaseIndex++;r.queue=[];r.revealed=[];r.resolving=-1;r.resolvingPid=null;if(r.phaseIndex>=phases.length)return houseReveal(r);r.phase=phases[r.phaseIndex];push(r,`Chuyển sang ${phaseVi(r.phase)}.`);sync(r);preparePhase(r)}
function houseReveal(r){r.status='round_end';r.phase='HOUSE REVEAL';const live=r.players.filter(p=>p.alive&&!p.ronin),groups={Lotus:[],Crane:[]};live.forEach(p=>groups[p.house]?.push(p));Object.values(groups).forEach(a=>a.sort((x,y)=>x.rank-y.rank));let winner=null;const a=groups.Lotus,b=groups.Crane;for(let i=0;i<Math.max(a.length,b.length);i++){const ar=a[i]?.rank??Infinity,br=b[i]?.rank??Infinity;if(ar!==br){winner=ar<br?'Lotus':'Crane';break}}const mm=r.players.find(p=>p.alive&&!p.ronin&&p.hand.some(c=>c.type==='MASTERMIND'));if(mm)winner=mm.house;r.winner=winner;if(winner){r.players.filter(p=>p.house===winner).forEach(p=>p.honor+=2+Math.floor(Math.random()*3));push(r,`${winner==='Lotus'?'Hoa Sen':'Sếu'} thắng vòng. Thành viên Nhà thắng nhận 1 token Danh dự (2–4 điểm).`)}else{live.forEach(p=>p.honor+=2);push(r,'Hai Nhà hòa: người sống nhận 2 Danh dự.')}const ronin=r.players.find(p=>p.ronin&&p.alive);if(ronin){ronin.honor+=2+Math.floor(Math.random()*3);push(r,`${ronin.name} là Lãng khách và sống sót nên nhận 1 token Danh dự.`)}sync(r);if(r.players.some(p=>p.honor>=10))r.status='ended'}

wss.on('connection',ws=>{let me=null,r=null;ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==='create'){const code=Math.random().toString(36).slice(2,7).toUpperCase();r={code,status:'lobby',players:[],host:null,round:0,log:[]};rooms.set(code,r);me={id:uid(),name:(m.name||'Người chơi').slice(0,20),ws,honor:0,alive:true,bot:false};r.players.push(me);r.host=me.id;send(me,'joined',{code,id:me.id});sync(r);return}
if(m.type==='join'){r=rooms.get(String(m.code||'').toUpperCase());if(!r||r.status!=='lobby'||r.players.length>=11)return send({ws},'error',{message:'Phòng không tồn tại, đã bắt đầu hoặc đã đầy.'});me={id:uid(),name:(m.name||'Người chơi').slice(0,20),ws,honor:0,alive:true,bot:false};r.players.push(me);send(me,'joined',{code:r.code,id:me.id});sync(r);return}
if(!me||!r)return;
if(m.type==='addBot'&&me.id===r.host&&r.status==='lobby'){if(r.players.length>=11)return send(me,'error',{message:'Phòng đã đủ 11 người.'});const n=r.players.filter(p=>p.bot).length+1;r.players.push({id:`bot-${uid()}`,name:`Bot ${n}`,honor:0,alive:true,bot:true,ronin:false,ws:null});push(r,`🤖 Đã thêm Bot ${n}.`);sync(r);return}
if(m.type==='start'&&me.id===r.host){if(r.players.length<4)return send(me,'error',{message:'Cần ít nhất 4 người.'});startRound(r)}
else if(m.type==='draftPick'&&r.status==='draft'&&!me.bot)pickDraft(r,me,m.cardId)
else if(m.type==='play'&&r.status==='night'&&!me.bot)play(r,me,m)
else if(m.type==='skip'&&r.status==='night'&&!me.bot)skip(r,me)
else if(m.type==='continueRound'&&r.status==='round_end'&&me.id===r.host)startRound(r)
else if(m.type==='pause'){if(r.status==='paused')r.status=r.previousStatus||'night';else{r.previousStatus=r.status;r.status='paused'}sync(r)}
else if(m.type==='end'&&me.id===r.host){r.status='ended';sync(r)}
else if(m.type==='chat'&&m.text)r.players.filter(p=>!p.bot).forEach(p=>send(p,'chat',{name:me.name,text:String(m.text).slice(0,300)}))
else if(m.type==='rename'){me.name=String(m.name||me.name).slice(0,20);sync(r)}
});ws.on('close',()=>{if(me&&r){me.ws=null;sync(r)}})});
server.listen(process.env.PORT||3000);
